const PRODUCTS=[
{id:1,n:"Nova X1 Pro",c:"Phones",p:899,s:799,e:"📱",r:4.8,stock:18,d:"Flagship AMOLED phone with 256GB storage and pro cameras.",sp:["6.7-inch AMOLED 120Hz","256GB","50MP camera","5000mAh"]},
{id:2,n:"PixelEdge 12",c:"Phones",p:699,e:"📱",r:4.6,stock:25,d:"Clean Android phone with a bright OLED display.",sp:["6.4-inch OLED","128GB","50MP camera","5G"]},
{id:3,n:"TitanBook Air 14",c:"Laptops",p:1299,s:1149,e:"💻",r:4.9,stock:9,d:"Slim productivity laptop for school, work and travel.",sp:["14-inch 2.8K","16GB RAM","512GB SSD","Wi-Fi 6E"]},
{id:4,n:"GameCore Pro 16",c:"Laptops",p:1799,e:"💻",r:4.7,stock:7,d:"High-performance gaming laptop with a fast display.",sp:["16-inch 165Hz","32GB RAM","1TB SSD","RTX graphics"]},
{id:5,n:"AeroBook 15",c:"Laptops",p:949,s:849,e:"💻",r:4.5,stock:13,d:"Balanced everyday laptop with a large screen.",sp:["15.6-inch FHD","16GB RAM","512GB SSD","Backlit keyboard"]},
{id:6,n:"SonicPods Max",c:"Audio",p:299,s:249,e:"🎧",r:4.8,stock:31,d:"Wireless over-ear headphones with active noise cancellation.",sp:["ANC","40h battery","Bluetooth 5.3","USB-C"]},
{id:7,n:"BassBeat Buds",c:"Audio",p:89,s:69,e:"🎧",r:4.4,stock:42,d:"Compact true wireless earbuds with punchy sound.",sp:["ANC","30h case","IPX5","Low latency"]},
{id:8,n:"StudioMic USB",c:"Audio",p:129,e:"🎙️",r:4.7,stock:22,d:"Plug-and-play USB microphone for streaming and calls.",sp:["Cardioid","24-bit audio","USB-C","Mute button"]},
{id:9,n:"Vision 27 4K",c:"Monitors",p:449,s:399,e:"🖥️",r:4.8,stock:12,d:"Sharp 4K monitor for creative work and gaming.",sp:["27-inch 4K","144Hz","HDR","USB-C"]},
{id:10,n:"UltraWide 34",c:"Monitors",p:599,e:"🖥️",r:4.6,stock:8,d:"Immersive ultrawide display for multitasking.",sp:["34-inch 3440x1440","165Hz","HDR","USB hub"]},
{id:11,n:"KeyPro Mechanical",c:"Accessories",p:119,s:99,e:"⌨️",r:4.7,stock:35,d:"Hot-swappable mechanical keyboard with RGB lighting.",sp:["Hot-swap","RGB","USB-C","N-key rollover"]},
{id:12,n:"SwiftMouse X",c:"Accessories",p:59,e:"🖱️",r:4.6,stock:50,d:"Lightweight wireless mouse built for productivity and gaming.",sp:["Wireless","8000 DPI","70h battery","6 buttons"]},
{id:13,n:"PowerHub 100W",c:"Accessories",p:79,e:"🔌",r:4.5,stock:44,d:"Compact GaN charger with multiple fast-charge ports.",sp:["100W GaN","3 USB-C","1 USB-A","PD 3.1"]},
{id:14,n:"GamePad Elite",c:"Gaming",p:149,s:129,e:"🎮",r:4.8,stock:17,d:"Precision wireless controller with adjustable triggers.",sp:["Wireless","Hall sticks","40h battery","USB-C"]},
{id:15,n:"GameBox SSD 2TB",c:"Gaming",p:179,e:"💾",r:4.9,stock:14,d:"Fast external SSD for games and media.",sp:["2TB","USB 3.2","1050MB/s","Shock resistant"]},
{id:16,n:"StreamCam 4K",c:"Gaming",p:169,s:149,e:"📷",r:4.6,stock:20,d:"4K webcam with autofocus for streaming and meetings.",sp:["4K 30fps","Autofocus","Dual mic","Privacy shutter"]},
{id:17,n:"HomeHub Mini",c:"Smart Home",p:59,s:49,e:"🏠",r:4.4,stock:28,d:"Compact smart assistant for your connected home.",sp:["Voice control","Wi-Fi","Multi-room","Smart routines"]},
{id:18,n:"GlowSmart Bulb",c:"Smart Home",p:24,e:"💡",r:4.3,stock:100,d:"Color smart bulb with scheduling and app control.",sp:["16M colors","Wi-Fi","Dimmable","Schedules"]},
{id:19,n:"WatchFit 3",c:"Wearables",p:229,s:199,e:"⌚",r:4.6,stock:16,d:"Fitness smartwatch with GPS and health tracking.",sp:["AMOLED","GPS","7-day battery","Water resistant"]},
{id:20,n:"TrackBand Lite",c:"Wearables",p:69,e:"⌚",r:4.2,stock:37,d:"Simple activity tracker with a bright display.",sp:["OLED","10-day battery","Sleep tracking","5ATM"]},
{id:21,n:"PowerBank 20K",c:"Accessories",p:49,s:39,e:"🔋",r:4.5,stock:55,d:"High-capacity power bank for phones and tablets.",sp:["20000mAh","65W output","USB-C","Digital display"]},
{id:22,n:"Mesh WiFi AX3000",c:"Networking",p:199,s:169,e:"📡",r:4.7,stock:11,d:"Whole-home Wi-Fi system with fast coverage.",sp:["Wi-Fi 6","3000Mbps","Mesh","App setup"]},
{id:23,n:"NAS Vault 4TB",c:"Storage",p:399,e:"🗄️",r:4.8,stock:6,d:"Personal network storage for backups and files.",sp:["4TB","RAID ready","2.5GbE","Remote access"]},
{id:24,n:"LaserPrint M200",c:"Office",p:229,e:"🖨️",r:4.4,stock:10,d:"Compact monochrome printer for home and office.",sp:["35 ppm","Duplex","Wi-Fi","Mobile print"]}
];